name: my-test

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linter
        run: make lint

      - name: pytest
        run: make pytest