name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pytest
        uses: make pytest
      - name: linter
        uses: make lint