name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v3
      - name: linter
        run: flake8 .

      - name: pytest
        run: pytest .
